# Generated by Django 3.1.4 on 2021-06-16 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_picture', models.ImageField(upload_to='images/')),
                ('flower_picture', models.ImageField(upload_to='images/')),
                ('common_name', models.CharField(max_length=100)),
                ('latin_name', models.TextField()),
                ('max_height', models.PositiveIntegerField()),
                ('max_age', models.PositiveIntegerField(blank=True)),
                ('company', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('in_flower', models.BooleanField(default=False)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('sponsor', models.TextField()),
                ('tree_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='trees.treetype')),
            ],
        ),
    ]
