# Generated by Django 3.1.4 on 2021-06-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treetype',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
