# Generated by Django 3.1.4 on 2021-06-23 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_auto_20210616_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='age',
        ),
        migrations.AddField(
            model_name='tree',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treetype',
            name='price',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
    ]
