# Generated by Django 3.1.4 on 2021-06-23 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trees', '0005_auto_20210623_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treetype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treetype',
            name='max_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
