# Generated by Django 3.1.4 on 2021-06-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_auto_20210623_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='planted',
            field=models.BooleanField(default=False),
        ),
    ]
