# Generated by Django 3.1.4 on 2021-06-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0008_auto_20210623_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='date_planted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
