# Generated by Django 3.1.4 on 2021-06-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0009_tree_date_planted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treetype',
            name='flower_picture',
            field=models.ImageField(blank=True, default='no-image-icon-7.gif', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='treetype',
            name='tree_picture',
            field=models.ImageField(blank=True, default='no-image-icon-7.gif', upload_to='images/'),
        ),
    ]
